[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gitlab.cee.redhat.com/service/uhc-sdk"
  version = "0.1.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
