[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/openshift-online/uhc-sdk-go"
  version = "0.1.14"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/onsi/gomega"
  revision = "v1.5.0"